### ISSUE TITLE
Bug: config can take multiple services and teams, code doesn't iterate 

### ISSUE THREAD

**Issue by barbequesauce** [trustpilot/pagerduty-notifier#6]
Looking through [here](https://github.com/trustpilot/pagerduty-notifier/blob/8a68150de84f6a94363c249a9018c61e786a45ec/src/pd.go#L152), it seems that although I have multiple services or teams defined in the config, it only uses the value of the first one in the list. I'm still learning go but I think it should iterate over the services?

**Comment by barbequesauce** [comment]
Also for teams....

**Comment by frese** [comment]
Hi @barbequesauce 

Super excited that you're using my notifier 😃 , I hope it works for you ?

It does loop through all include filters [here](https://github.com/trustpilot/pagerduty-notifier/blob/8a68150de84f6a94363c249a9018c61e786a45ec/src/pd.go#L150), which can be either a service or a team.
As soon as one include filter does match, it will continue to check for possible exclude filters.

If you have problems setting up the filters I might be able to help if you post your settings file.


br
Allan

**Comment by barbequesauce** [comment]
Thanks! Yeah still in the setup phase...

here's my current pagerduty.ini. I dialed it back to one team, but I'm still receiving every PD incident instead of just the ones for that team. Previously I tried a single and multiple services, still the same behavior:
```
[pagerduty]
# You need to add your Pagerduty API token
token = BLAHBLAHBLAH
# default interval between poll's is 30 sec.
interval = 30
 
# timezone for incidents, defaults to UTC
timezone = Europe/Copenhagen
 
# Optional query parameters for the Pagerduty API
# Use comma separated lists of names (for users also email). You will usually only use one of them.
# If left blank, you will receive all incidents from the account.
teams = Incident Management Team
users =
services =
 
# include and exclude filters is applied (in that order) to all incidents coming from PD API
# with the above query parameters.
 
# Format is "<property.[!]name> = <incident filter>"" where:
#    <property> is one of "team" or "service"
#    <name> which team or service this filter should be applied
#           optionally the <name> could be prefixed with [!] to indicate the oppersite match
#    <incident filter> regular expression to match the title of the incident
#
# if no include filters is defined, default is to include every incident
 
 
# This will include incidents from all services except the "test" service
[include]
service.!test = .*
 
# This will exclude all incidents to "devops" team that matches ".*test.*"
[exclude]
team.devops = .*test.*
```

**Comment by frese** [comment]
Without knowing your Pagerduty setup wrt. teams or services, I'd guess that either the [pagerduty] teams parameter isn't read correctly. eg. if team "Incident Management Team" isn't found. You can take a look in the console, search for this [line](https://github.com/trustpilot/pagerduty-notifier/blob/master/src/pd.go#L64).

Another issue could be the include filter `service.!test = .*` - this will include incidents from all services except the `test` service. Maybe it's better to set this as an exclude filter `service.test = .*`

**Comment by barbequesauce** [comment]
Thanks - I'd misunderstood the filtering approach. For those who struggle with it, here's my final pagerduty.ini - note the service1 etc are really the seven-character PXXXXXX codes shown in the URL for the given service you're looking for. Also, I do not have a team called potato or a service called test.

```
[pagerduty]
# You need to add your Pagerduty API token
token = BLAHBLAhBLAH
# default interval between poll's is 30 sec.
interval = 30
 
# timezone for incidents, defaults to UTC
timezone = Europe/Copenhagen
 
# Optional query parameters for the Pagerduty API
# Use comma separated lists of names (for users also email). You will usually only use one of them.
# If left blank, you will receive all incidents from the account.
teams =
users =
services = service1, service2, service3, service4
 
# include and exclude filters is applied (in that order) to all incidents coming from PD API
# with the above query parameters.
 
# Format is "<property.[!]name> = <incident filter>"" where:
#    <property> is one of "team" or "service"
#    <name> which team or service this filter should be applied
#           optionally the <name> could be prefixed with [!] to indicate the oppersite match
#    <incident filter> regular expression to match the title of the incident
#
# if no include filters is defined, default is to include every incident
 
 
# This will include incidents from all services except the "test" service
[include]
service.!test = .*
 
# This will exclude all incidents to "devops" team that matches ".*test.*"
[exclude]
team.!potato = .*

```
